name: Pull Request build

on:

  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Run Gradle
        uses: burrunan/gradle-cache-action@v1
        env:
          GRADLE_ENTERPRISE_URL: https://ge.spring.io/
        with:
          arguments: check api

      - name: Capture Test Results
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: '*/build/reports/tests/**/*.*'
          retention-days: 3
